#google map custom marker icon - .png fallback for IE11
is_internetExplorer11 = navigator.userAgent.toLowerCase().indexOf('trident') > -1
marker_url = if is_internetExplorer11 then 'img/cd-icon-location.png' else 'img/cd-icon-location.svg'
marker_url0 = if is_internetExplorer11 then 'img/cd-icon-location0.png' else 'img/cd-icon-location0.svg'
#define the basic color of your map, plus a value for saturation and brightness
main_color = '#2d313f'
saturation_value = -20
brightness_value = 5
#we define here the style of the map
style = [
  {
    'featureType': 'administrative'
    'elementType': 'all'
    'stylers': [
      { 'visibility': 'on' }
      { 'lightness': 33 }
    ]
  }
  {
    'featureType': 'landscape'
    'elementType': 'all'
    'stylers': [ { 'color': '#f2e5d4' } ]
  }
  {
    'featureType': 'poi.park'
    'elementType': 'geometry'
    'stylers': [ { 'color': '#c5dac6' } ]
  }
  {
    'featureType': 'poi.park'
    'elementType': 'labels'
    'stylers': [
      { 'visibility': 'on' }
      { 'lightness': 20 }
    ]
  }
  {
    'featureType': 'road'
    'elementType': 'all'
    'stylers': [ { 'lightness': 20 } ]
  }
  {
    'featureType': 'road.highway'
    'elementType': 'geometry'
    'stylers': [ { 'color': '#c5c6c6' } ]
  }
  {
    'featureType': 'road.arterial'
    'elementType': 'geometry'
    'stylers': [ { 'color': '#e4d7c6' } ]
  }
  {
    'featureType': 'road.local'
    'elementType': 'geometry'
    'stylers': [ { 'color': '#fbfaf7' } ]
  }
  {
    'featureType': 'water'
    'elementType': 'all'
    'stylers': [
      { 'visibility': 'on' }
      { 'color': '#acbcc9' }
    ]
  }
]

#set google map options
map_options = 
  center: new (google.maps.LatLng)(_map.latitude_center, _map.longitude_center)
  zoom: _map.map_zoom
  panControl: false
  zoomControl: false
  mapTypeControl: false
  streetViewControl: false
  mapTypeId: google.maps.MapTypeId.ROADMAP
  scrollwheel: true
  #styles: style
#inizialize the map
map = new (google.maps.Map)(document.getElementById('google-container'), map_options)
#add a custom marker to the map				

CustomZoomControl = (controlDiv, map) ->
  #grap the zoom elements from the DOM and insert them in the map 
  controlUIzoomIn = document.getElementById('cd-zoom-in')
  controlUIzoomOut = document.getElementById('cd-zoom-out')
  controlDiv.appendChild controlUIzoomIn
  controlDiv.appendChild controlUIzoomOut
  # Setup the click event listeners and zoom-in or out according to the clicked element
  google.maps.event.addDomListener controlUIzoomIn, 'click', ->
    map.setZoom map.getZoom() + 1

  google.maps.event.addDomListener controlUIzoomOut, 'click', ->
    map.setZoom map.getZoom() - 1
  
marker = Array()
infowindow = Array()

_marker = new (google.maps.Marker)(
  position: new (google.maps.LatLng)(_map.latitude, _map.longitude)
  map: map
  visible: true
  icon: marker_url)

_infowindow = new google.maps.InfoWindow
  content: map.content

google.maps.event.addListener _marker, 'click', ->
  _infowindow.open map, _marker




$.each _map.dots, (index, value) ->
  marker[index] = new (google.maps.Marker)(
    position: new (google.maps.LatLng)(value[0], value[1])
    map: map
    visible: true
    icon: marker_url0)

  infowindow[index] = new google.maps.InfoWindow
    content: '<h2>' +value[2]+ '</h2><p>' +value[3]+ ', ' +value[4]+ '</p>'

  google.maps.event.addListener marker[index], 'click', ->
    infowindow[index].open map, marker[index]




zoomControlDiv = document.createElement('div')
zoomControl = new CustomZoomControl(zoomControlDiv, map)
#insert the zoom div on the top left of the map
#add custom buttons for the zoom-in/zoom-out on the map


map.controls[google.maps.ControlPosition.LEFT_TOP].push zoomControlDiv

# ---
# generated by js2coffee 2.0.1